`ifndef DEFINE_STATE

typedef enum logic [4:0] {
	S_WAIT_NEW_PIXEL_ROW,
	S_NEW_PIXEL_ROW_DELAY_1,
	S_NEW_PIXEL_ROW_DELAY_2,
	S_NEW_PIXEL_ROW_DELAY_3,
	S_NEW_PIXEL_ROW_DELAY_4,
	S_NEW_PIXEL_ROW_DELAY_5,
	S_FETCH_PIXEL_DATA_0,
	S_FETCH_PIXEL_DATA_1,
	S_FETCH_PIXEL_DATA_2,
	S_FETCH_PIXEL_DATA_3,
	S_IDLE,
	S_FILL_SRAM_RED_SEGMENT_FIRST,
	S_FILL_SRAM_RED_SEGMENT_SECOND,
	S_FILL_SRAM_GREEN_SEGMENT_FIRST,
	S_FILL_SRAM_GREEN_SEGMENT_SECOND,
	S_FILL_SRAM_BLUE_SEGMENT_EVEN,
	S_FILL_SRAM_BLUE_SEGMENT_ODD,
	S_FINISH_FILL_SRAM
} state_type;

parameter NUM_ROW_RECTANGLE = 8,
          NUM_COL_RECTANGLE = 8,
          RECT_WIDTH = 40,
          RECT_HEIGHT = 30,
          VIEW_AREA_LEFT = 160,
          VIEW_AREA_RIGHT = 480,
          VIEW_AREA_TOP = 120,
          VIEW_AREA_BOTTOM = 360;

// Define the offset for Green and Blue data in the memory		
parameter RED_BASE_ADDRESS = 18'd146944,
	GREEN_BASE_ADDRESS = 18'd185344,
	BLUE_EVEN_BASE_ADDRESS = 18'd223744,
	BLUE_ODD_BASE_ADDRESS = 18'd242944;

`define DEFINE_STATE 1
`endif

